export * from './types';
export { detectPineScriptType, compiledScriptType } from './strategyDetector';
export { executeStrategy, sliceCandles, toStrategySettings } from './strategyExecutor';
export type { ExecuteStrategyArgs, ExecuteStrategyOutcome } from './strategyExecutor';
export { buildEquityCurve, buildOpenPosition, buildPositions, buildTrades } from './strategyAdapter';
export type { OpenLotSnapshot } from './strategyAdapter';
export { computeSummary, equityPhases, periodPerformance } from './metrics';
export { buildStrategyMarkers, buildPositionBackground } from './markers';
export type { MarkerInfo, StrategyMarkers } from './markers';
export { StrategyCache, cacheKey } from './strategyCache';
export { describeUnsupported, findUnsupportedStrategyCalls } from './unsupported';
export type { UnsupportedFeature } from './unsupported';
export { exportTradesCsv, exportSummaryJson } from './exporters';
